--[[
DewDropDown.lua
Defines the table listings for the dropdown lists.
]]

--Invoke all libraries
local AL = LibStub("AceLocale-3.0"):GetLocale("AtlasLoot");
local BabbleBoss = AtlasLoot_GetLocaleLibBabble("LibBabble-Boss-3.0")
local BabbleFaction = AtlasLoot_GetLocaleLibBabble("LibBabble-Faction-3.0")
local BabbleZone = AtlasLoot_GetLocaleLibBabble("LibBabble-Zone-3.0")
local BabbleInventory = AtlasLoot_GetLocaleLibBabble("LibBabble-Inventory-3.0")

--This is a multi-layer table defining the main loot listing.
--Entries have the text to display, loot table or sub table to link to and if the link is to a loot table or sub table
AtlasLoot_DewDropDown = {
	[1] = {
		[AL["Classic Instances"]] = {
			[1] = {
				{ BabbleZone["Gnomeregan"], "Gnomeregan1", "Table" },
			},
			[2] = {
				[BabbleZone["Dire Maul"]] = {
					{ BabbleZone["Dire Maul (East)"], "DireMaulEast", "Submenu" },
					{ BabbleZone["Dire Maul (West)"], "DireMaulWest", "Submenu" },
					{ BabbleZone["Dire Maul (North)"], "DireMaulNorth", "Submenu" },
				},
			},
			[3] = {
				{ BabbleZone["Zul'Farrak"], "ZulFarrak", "Submenu" },
			},
			[4] = {
				{ BabbleZone["Shadowfang Keep"], "ShadowfangKeep1", "Table" },
			},
			[5] = {
				{ BabbleZone["Razorfen Downs"], "RazorfenDowns1", "Table" },
			},
			[6] = {
				{ BabbleZone["Razorfen Kraul"], "RazorfenKraul1", "Table" },
			},
			[7] = {
				{ BabbleZone["Maraudon"], "Maraudon1", "Table" },
			},
			[8] = {
				{ BabbleZone["The Deadmines"], "TheDeadmines1", "Table" },
			},
			[9] = {
				{ BabbleZone["Scarlet Monastery"], "Scarlet Monastery", "Submenu" },
			},
			[10] = {
				{ BabbleZone["Scholomance"], "Scholomance", "Submenu" },
			},
			[11] = {
				{ BabbleZone["Blackfathom Deeps"], "BlackfathomDeeps1", "Table" },
			},
			[12] = {
				{ BabbleZone["Ragefire Chasm"], "RagefireChasm", "Table" },
			},
			[13] = {
				{ BabbleZone["Wailing Caverns"], "WailingCaverns1", "Table" },
			},
			[14] = {
				{ BabbleZone["Stratholme"], "Stratholme", "Submenu" },
			},
			[15] = {
				{ BabbleZone["The Stockade"], "TheStockade", "Table" },
			},
			[16] = {
				{ BabbleZone["Uldaman"], "Uldaman", "Submenu" },
			},
			[17] = {
				{ BabbleZone["The Temple of Atal'Hakkar"], "SunkenTemple", "Submenu" },
			},
			[18] = {
				[BabbleZone["Blackrock Mountain"]] = {
				{ BabbleZone["Upper Blackrock Spire"], "UpperBlackrock", "Submenu" },
				{ BabbleZone["Blackrock Depths"], "BlackrockDepths", "Submenu" },
				{ BabbleZone["Lower Blackrock Spire"], "LowerBlackrock", "Submenu" },
				},
			},
		},
	},
	[2] = {
		[AL["Classic Raids"]] = {
			[1] = {
				{ BabbleZone["Zul'Gurub"], "ZulGurub", "Submenu" },
			},
			[2] = {
				{ BabbleZone["Blackwing Lair"], "BlackwingLair", "Submenu" },
			},
			[3] = {
				{ BabbleZone["Molten Core"], "MoltenCore", "Submenu" },
			},
			[4] = {
				{ BabbleZone["Ruins of Ahn'Qiraj"], "RuinsofAQ", "Submenu" },
			},
			[5] = {
				{ BabbleZone["Temple of Ahn'Qiraj"], "TempleofAQ", "Submenu" },
			},
		},
	},
	[3] = {
		[AL["BC Instances"]] = {
			[1] = {
				[BabbleZone["Auchindoun"]] = {
					{ BabbleZone["Auchenai Crypts"], "AuchCrypts", "Submenu" },
					{ BabbleZone["Mana-Tombs"], "AuchManaTombs", "Submenu" },
					{ BabbleZone["Sethekk Halls"], "AuchSethekk", "Submenu" },
					{ BabbleZone["Shadow Labyrinth"], "AuchShadowLab", "Submenu" },
				}, 
			},
			[2] = {
				[BabbleZone["Tempest Keep"]] = {
					{ BabbleZone["The Arcatraz"], "TKArc", "Submenu" },
					{ BabbleZone["The Botanica"], "TKBot", "Submenu" },
					{ BabbleZone["The Mechanar"], "TKMech", "Submenu" },
				},
			},
			[3] = {
				[BabbleZone["Caverns of Time"]] = {
					{ BabbleZone["Old Hillsbrad Foothills"], "CoTOldHillsbrad", "Submenu" },
					{ BabbleZone["The Black Morass"], "CoTBlackMorass", "Submenu" },
				},
			},
			[4] = {
				[BabbleZone["Coilfang Reservoir"]] = {
					{ BabbleZone["The Underbog"], "CFRUnderbog", "Submenu" },
					{ BabbleZone["The Steamvault"], "CFRSteamvault", "Submenu" },
					{ BabbleZone["The Slave Pens"], "CFRSlavePens", "Submenu" },
				},
			},
			[5] = {
				{ BabbleZone["Magisters' Terrace"], "MagistersTerrace", "Submenu" },
			},
			[6] = {
				[BabbleZone["Hellfire Citadel"]] = {
					{ BabbleZone["Hellfire Ramparts"], "HCRamparts", "Submenu" },
					{ BabbleZone["The Blood Furnace"], "HCFurnace", "Submenu" },
					{ BabbleZone["The Shattered Halls"], "HCShatteredHalls", "Submenu" },
				}, 
			},
		},
	},
	[4] = {
		[AL["BC Raids"]] = {
			[1] = {
					{ BabbleZone["Hyjal Summit"], "CoTHyjal", "Submenu" },
			},
			[2] = {
					{ BabbleZone["Serpentshrine Cavern"], "CFRSerpentshrine", "Submenu" },
			},
			[3] = {
				{ BabbleZone["Zul'Aman"], "ZulAman", "Submenu" },
			},
			[4] = {
				{ BabbleZone["Karazhan"], "Karazhan", "Submenu" },
			},
			[5] = {
					{ BabbleZone["Tempest Keep"]..": "..BabbleZone["The Eye"], "TKEye", "Submenu" },
			},
			[6] = {
				{ BabbleZone["Gruul's Lair"], "Gruul", "Submenu" },
			},
			[7] = {
					{ BabbleZone["Magtheridon's Lair"], "HCMagtheridon", "Table" },
			},
			[8] = {
				{ BabbleZone["Sunwell Plateau"], "SunwellPlateau", "Submenu" },
			},
			[9] = {
				{ BabbleZone["Black Temple"], "BlackTemple", "Submenu" },
			},
		},
	},
	[5] = {
		[AL["WotLK Instances"]] = {
			[1] = {
				{ BabbleZone["Azjol-Nerub"], "AzjolNerub", "Submenu" },
			},
			[2] = {
				{ BabbleZone["The Violet Hold"], "TheVioletHold", "Submenu" },
			},
			[3] = {
				{ BabbleZone["Ahn'kahet: The Old Kingdom"], "Ahnkahet", "Submenu" },
			},
			[4] = {
				{ BabbleZone["Utgarde Pinnacle"], "UtgardePinnacle", "Submenu" },
			},
			[5] = {
				{ BabbleZone["Gundrak"], "Gundrak", "Submenu" },
			},
			[6] = {
				{ BabbleZone["Trial of the Champion"], "TrialoftheChampion", "Submenu" },
			},
			[7] = {
				{ BabbleZone["Drak'Tharon Keep"], "DrakTharonKeep", "Submenu" },
			},
			[8] = {
				{ BabbleZone["Utgarde Keep"], "UtgardeKeep", "Submenu" },
			},
			[9] = {
				{ BabbleZone["The Nexus"], "TheNexus", "Submenu" },
			},
			[10] = {
				{ BabbleZone["The Oculus"], "TheOculus", "Submenu" },
			},
			[11] = {
				{ BabbleZone["Caverns of Time"]..": "..BabbleZone["The Culling of Stratholme"], "CoTStratholme", "Submenu" },
			},
			[12] = {
				[BabbleZone["Icecrown Citadel"]] = {
				{ BabbleZone["Halls of Reflection"], "HallsofReflection", "Submenu" },
				{ BabbleZone["The Forge of Souls"], "ForgeofSouls", "Submenu" },
				{ BabbleZone["Pit of Saron"], "PitofSaron", "Submenu" },
				}, 
			},
			[13] = {
				{ BabbleZone["Halls of Stone"], "HallsofStone", "Submenu" },
			},
			[14] = {
				{ BabbleZone["Halls of Lightning"], "HallsofLightning", "Submenu" },
			},
		},
	},
	[6] = {
		[AL["WotLK Raids"]] = {
			[1] = {
				{ BabbleZone["Trial of the Crusader"], "TrialoftheCrusader_A", "Submenu" },
			},
			[2] = {
				{ BabbleZone["Onyxia's Lair"], "Onyxia_1", "Table" },
			},
			[3] = {
				{ BabbleZone["Naxxramas"], "Naxxramas80", "Submenu" },
			},
			[4] = {
				{ BabbleZone["The Obsidian Sanctum"], "Sartharion", "Table" },
			},
			[5] = {
				{ BabbleZone["The Eye of Eternity"], "Malygos", "Table" },
			},
            [6] = {
				{ BabbleZone["The Ruby Sanctum"], "Halion", "Table" },
			},
			[7] = {
				{ BabbleZone["Vault of Archavon"], "VaultofArchavon_A", "Submenu" },
			},
			[8] = {
				{ BabbleZone["Ulduar"], "Ulduar", "Submenu" },
			},
			[9] = {
				{ BabbleZone["Icecrown Citadel"], "IcecrownCitadel", "Submenu" },
			},
		},
	},
	[7] = {
		[AL["Epochal mode"]] = {
			[1] = {
				{ AL["EpochalWeapon"], "EpochalWeapon", "Submenu" },
			},
			[2] = {
				{ AL["EpochalCloth"], "EpochalCloth", "Submenu" },
			},
			[3] = {
				{ AL["EpochalLeather"], "EpochalLeather", "Submenu" },
			},
			[4] = {
				{ AL["EpochalMail"], "EpochalMail", "Submenu" },
			},
			[5] = {
				{ AL["EpochalPlait"], "EpochalPlait", "Submenu" },
			},
			[6] = {
				{ AL["EpochalСloak"], "EpochalСloak", "Submenu" },
			},
			[7] = {
				{ AL["EpochalNeck"], "EpochalNeck", "Submenu" },
			},
			[8] = {
				{ AL["EpochalRight"], "EpochalRight", "Submenu" },
			},				
		},
	},
	[8] = {
		[AL["Sirus Raids"]] = {
			[1] = {
				{ AL["Bronze Sanctuary"], "BronzeSanctuary", "Submenu" },
			},	
			[2] = {
				[ AL["Tol'Garod Prison"]] = {
				{ AL["Tol'Garod Prison5"], "Tol'Garod Prison5", "Submenu" },
				{ AL["Tol'Garod Prison2"], "Tol'Garod Prison2", "Submenu" },
				{ AL["Tol'Garod Prison3"], "Tol'Garod Prison3", "Submenu" },
				{ AL["Tol'Garod Prison4"], "Tol'Garod Prison4", "Submenu" },
				},
			},	
			[3] = {
				{ AL["Zort"], "Zort", "Submenu" },
			},			
		},
	},
	[9] = {
		[ AL["DailyMenuMain"]] = {
			[1] = {
				{ AL["DailyMenu"], "DAILYMENU", "Table" },
				},
			[2] = {
				[ AL["DailySpecT4"]] = {
					{ AL["T4DQDeathKnightDPS"], "T4DQDeathKnightDPS", "Table" },
					{ AL["T4DQDeathKnightDPSfrost"], "T4DQDeathKnightDPSfrost", "Table" },
					{ AL["T4DQDeathKnightDPSblood"], "T4DQDeathKnightDPSblood", "Table" },
					{ AL["T4DQDeathKnightTank"], "T4DQDeathKnightTank", "Table" },
					{ AL["T4DQDruidBalance"], "T4DQDruidBalance", "Table" },
					{ AL["T4DQDruidFeral"], "T4DQDruidFeral", "Table" },
					{ AL["T4DQDruidFeralDD"], "T4DQDruidFeralDD", "Table" },
					{ AL["T4DQDruidRestoration"], "T4DQDruidRestoration", "Table" },
					{ AL["T4DQHunter"], "T4DQHunter", "Table" },
					{ AL["T4DQHuntermm"], "T4DQHuntermm", "Table" },
					{ AL["T4DQHuntersu"], "T4DQHuntersu", "Table" },
					{ AL["T4DQMage"], "T4DQMage", "Table" },
					{ AL["T4DQMagefier"], "T4DQMagefier", "Table" },
					{ AL["T4DQMagefrost"], "T4DQMagefrost", "Table" },
					{ AL["T4DQPaladinHoly"], "T4DQPaladinHoly", "Table" },
					{ AL["T4DQPaladinProtection"], "T4DQPaladinProtection", "Table" },
					{ AL["T4DQPaladinRetribution"], "T4DQPaladinRetribution", "Table" },
					{ AL["T4DQPriestHolydz"], "T4DQPriestHolydz", "Table" },
					{ AL["T4DQPriestHoly"], "T4DQPriestHoly", "Table" },
					{ AL["T4DQPriestShadow"], "T4DQPriestShadow", "Table" },
					{ AL["T4DQRogue"], "T4DQRogue", "Table" },
					{ AL["T4DQRoguekomb"], "T4DQRoguekomb", "Table" },
					{ AL["T4DQRogueshd"], "T4DQRogueshd", "Table" },
					{ AL["T4DQShamanElemental"], "T4DQShamanElemental", "Table" },
					{ AL["T4DQShamanEnhancement"], "T4DQShamanEnhancement", "Table" },
					{ AL["T4DQShamanRestoration"], "T4DQShamanRestoration", "Table" },
					{ AL["T4DQWarlock"], "T4DQWarlock", "Table" },
					{ AL["T4DQWarlockdeam"], "T4DQWarlockdeam", "Table" },
					{ AL["T4DQWarlockdestr"], "T4DQWarlockdestr", "Table" },
					{ AL["T4DQWarriorarm"], "T4DQWarriorarm", "Table" },
					{ AL["T4DQWarriorFury"], "T4DQWarriorFury", "Table" },
					{ AL["T4DQWarriorProtection"], "T4DQWarriorProtection", "Table" },
				},
			},	
			[3] = {
				[ AL["DailySpecT5"]] = {
					{ AL["T5DQDeathKnightDPS"], "T4DQDeathKnightDPS", "Table" },
					{ AL["T5DQDeathKnightDPSfrost"], "T4DQDeathKnightDPSfrost", "Table" },
					{ AL["T5DQDeathKnightDPSblood"], "T4DQDeathKnightDPSblood", "Table" },
					{ AL["T5DQDeathKnightTank"], "T4DQDeathKnightTank", "Table" },
					{ AL["T5DQDeathKnightTankfrost"], "T4DQDeathKnightTank", "Table" },
					{ AL["T5DQDeathKnightTankblood"], "T4DQDeathKnightTank", "Table" },
					{ AL["T5DQDruidBalance"], "T4DQDruidBalance", "Table" },
					{ AL["T5DQDruidFeral"], "T4DQDruidFeral", "Table" },
					{ AL["T5DQDruidFeralDD"], "T4DQDruidFeralDD", "Table" },
					{ AL["T5DQDruidRestoration"], "T4DQDruidRestoration", "Table" },
					{ AL["T5DQHunter"], "T4DQHunter", "Table" },
					{ AL["T5DQHuntermm"], "T4DQHuntermm", "Table" },
					{ AL["T5DQHuntersu"], "T4DQHuntersu", "Table" },
					{ AL["T5DQMage"], "T4DQMage", "Table" },
					{ AL["T5DQMagefier"], "T4DQMagefier", "Table" },
					{ AL["T5DQMagefrost"], "T4DQMagefrost", "Table" },
					{ AL["T5DQPaladinHoly"], "T4DQPaladinHoly", "Table" },
					{ AL["T5DQPaladinProtection"], "T4DQPaladinProtection", "Table" },
					{ AL["T5DQPaladinRetribution"], "T4DQPaladinRetribution", "Table" },
					{ AL["T5DQPriestHolydz"], "T4DQPriestHolydz", "Table" },
					{ AL["T5DQPriestHoly"], "T4DQPriestHoly", "Table" },
					{ AL["T5DQPriestShadow"], "T4DQPriestShadow", "Table" },
					{ AL["T5DQRogue"], "T4DQRogue", "Table" },
					{ AL["T5DQRoguekomb"], "T4DQRoguekomb", "Table" },
					{ AL["T5DQRogueshd"], "T4DQRogueshd", "Table" },
					{ AL["T5DQShamanElemental"], "T4DQShamanElemental", "Table" },
					{ AL["T5DQShamanEnhancement"], "T4DQShamanEnhancement", "Table" },
					{ AL["T5DQShamanRestoration"], "T4DQShamanRestoration", "Table" },
					{ AL["T5DQWarlock"], "T4DQWarlock", "Table" },
					{ AL["T5DQWarlockdeam"], "T4DQWarlockdeam", "Table" },
					{ AL["T5DQWarlockdestr"], "T4DQWarlockdestr", "Table" },
					{ AL["T5DQWarriorarm"], "T4DQWarriorarm", "Table" },
					{ AL["T5DQWarriorFury"], "T4DQWarriorFury", "Table" },
					{ AL["T5DQWarriorProtection"], "T4DQWarriorProtection", "Table" },
				},
				
			},
		},
	},
	[10] = {
		{ AL["Crafting"], "CRAFTINGMENU", "Table" },
	},
	[11] = {
		{ AL["Sets/Collections"], "SETMENU", "Table" },
	},
	[12] = {
		{ AL["PvP Rewards"], "PVPMENU", "Table" },
	},
	[13] = {
		{ AL["World Bosses"], "WorldBosses", "Submenu" },
	},
	[14] = {
		{ AL["Reputation Factions"], "REPMENU", "Table" },
	},
	[15] = {
		{ AL["World Events"], "WORLDEVENTMENU", "Table" },
	},
	[16] = {
		{ AL["Kategoria"], "KATEGORIAMENU_x2", "Table" },
	},
};

--This table defines all the subtables needed for the full menu
--Each sub table entry contains the text entry and the loot table that goes wih it
AtlasLoot_DewDropDown_SubTables = {
	["BlackrockDepths"] = {
		{ "", "BRDPyron" },
		{ "", "BRDLordRoccor" },
		{ "", "BRDHighInterrogatorGerstahn" },
		{ "", "BRDArena" },
		{ "", "BRDTheldren" },
		{ "", "BRDHoundmaster" },
		{ "", "BRDPyromantLoregrain" },
		{ "", "BRDTheVault" },
		{ "", "BRDWarderStilgiss" },
		{ "", "BRDVerek" },
		{ "", "BRDFineousDarkvire" },
		{ "", "BRDLordIncendius" },
		{ "", "BRDBaelGar" },
		{ "", "BRDGeneralAngerforge" },
		{ "", "BRDGolemLordArgelmach" },
		{ "", "BRDGuzzler" },
		{ "", "CorenDirebrew" },
		{ "", "BRDFlamelash" },
		{ "", "BRDPanzor" },
		{ "", "BRDTomb" },
		{ "", "BRDMagmus" },
		{ "", "BRDImperatorDagranThaurissan" },
		{ "", "BRDPrincess" },
		{ "", "BRDBSPlans" },
		{ "", "BRDTrash" },
		{ "", "VWOWSets1" },
	},
	["LowerBlackrock"] = {
		{ "", "LBRSSpirestoneButcher" },
		{ "", "LBRSOmokk" },
		{ "", "LBRSSpirestoneLord" },
		{ "", "LBRSLordMagus" },
		{ "", "LBRSVosh" },
		{ "", "LBRSVoone" },
		{ "", "LBRSGrayhoof" },
		{ "", "LBRSGrimaxe" },
		{ "", "LBRSSmolderweb" },
		{ "", "LBRSCrystalFang" },
		{ "", "LBRSDoomhowl" },
		{ "", "LBRSZigris" },
		{ "", "LBRSHalycon" },
		{ "", "LBRSSlavener" },
		{ "", "LBRSBashguud" },
		{ "", "LBRSWyrmthalak" },
		{ "", "LBRSFelguard" },
		{ "", "LBRSTrash" },
		{ "", "VWOWSets3" },
	},
	["UpperBlackrock"] = {
		{ "", "UBRSEmberseer" },
		{ "", "UBRSSolakar" },
		{ "", "UBRSFLAME" },
		{ "", "UBRSRunewatcher" },
		{ "", "UBRSAnvilcrack" },
		{ "", "UBRSRend" },
		{ "", "UBRSGyth" },
		{ "", "UBRSBeast" },
		{ "", "UBRSValthalak" },
		{ "", "UBRSDrakkisath" },
		{ "", "UBRSTrash" },
		{ "", "VWOWSets3" },
	},
	["BlackwingLair"] = {
		{ "", "BWLRazorgore" },
		{ "", "BWLVaelastrasz" },
		{ "", "BWLLashlayer" },
		{ "", "BWLFiremaw" },
		{ "", "BWLEbonroc" },
		{ "", "BWLFlamegor" },
		{ "", "BWLChromaggus" },
		{ "", "BWLNefarian1" },
		{ "", "BWLTrashMobs" },
	},
	["Karazhan"] = {
		{ "", "KaraAttumen" },
		{ "", "KaraMoroes" },
		{ "", "KaraMaiden" },
		{ "", "KaraOperaEvent" },
		{ "", "KaraCurator" },
		{ "", "KaraIllhoof" },
		{ "", "KaraAran" },
		{ "", "KaraNetherspite" },
		{ "", "KaraNightbane" },
		{ "", "KaraChess" },
		{ "", "KaraPrince" },
		{ "", "KaraNamed" },
		{ "", "KaraTrash" },
	},
	["MagistersTerrace"] = {
		{ "", "SMTFireheart" },
		{ "", "SMTVexallus" },
		{ "", "SMTDelrissa" },
		{ "", "SMTKaelthas" },
	},
	["MoltenCore"] = {
		{ "", "MCLucifron" },
		{ "", "MCMagmadar" },
		{ "", "MCGehennas" },
		{ "", "MCGarr" },
		{ "", "MCShazzrah" },
		{ "", "MCGeddon" },
		{ "", "MCGolemagg" },
		{ "", "MCSulfuron" },
		{ "", "MCMajordomo" },
		{ "", "MCRagnaros" },
		{ "", "MCTrashMobs" },
		{ "", "MCRANDOMBOSSDROPPS" },
	},
	["Scarlet Monastery"] = {
		{ BabbleZone["Armory"], "SMHerod" },
		{ "", "SMCathedral" },
		{ "", "SMGraveyard" },
		{ "", "SMLibrary" },
		{ "", "SMTrash" },
		{ AL["Set: Chain of the Scarlet Crusade"], "VWOWSets1" },
	},
	["Scholomance"] = {
		{ "", "SCHOLOBloodStewardofKirtonos" },
		{ "", "SCHOLOKirtonostheHerald" },
		{ "", "SCHOLOJandiceBarov" },
		{ "", "SCHOLORattlegore" },
		{ "", "SCHOLODeathKnight" },
		{ "", "SCHOLOMarduk" },
		{ "", "SCHOLOVectus" },
		{ "", "SCHOLORasFrostwhisper" },
		{ "", "SCHOLOKormok" },
		{ "", "SCHOLOInstructorMalicia" },
		{ "", "SCHOLODoctorTheolenKrastinov" },
		{ "", "SCHOLOLorekeeperPolkelt" },
		{ "", "SCHOLOTheRavenian" },
		{ "", "SCHOLOLordAlexeiBarov" },
		{ "", "SCHOLOLadyIlluciaBarov" },
		{ "", "SCHOLODarkmasterGandling" },
		{ "", "SCHOLOTrash" },
		{ AL["Set: Necropile Raiment"], "VWOWScholo" },
		{ AL["Set: Cadaverous Garb"], "VWOWScholo" },
		{ AL["Set: Bloodmail Regalia"], "VWOWScholo" },
		{ AL["Set: Deathbone Guardian"], "VWOWScholo" },
	},
	["Stratholme"] = {
		{ BabbleBoss["Skul"], "STRATSkull" },
		{ AtlasLoot_TableNames["STRATStratholmeCourier"][1], "STRATStratholmeCourier" },
		{ BabbleBoss["Fras Siabi"], "STRATFrasSiabi" },
		{ AtlasLoot_TableNames["STRATAtiesh"][1], "STRATAtiesh" },
		{ BabbleBoss["Hearthsinger Forresten"], "STRATHearthsingerForresten" },
		{ BabbleBoss["The Unforgiven"], "STRATTheUnforgiven" },
		{ BabbleBoss["Timmy the Cruel"], "STRATTimmytheCruel" },
		{ AtlasLoot_TableNames["STRATMalorsStrongbox"][1], "STRATMalorsStrongbox" },
		{ BabbleBoss["Crimson Hammersmith"], "STRATCrimsonHammersmith" },
		{ AtlasLoot_TableNames["STRATBSPlansSerenity"][1], "STRATBSPlansSerenity" },
		{ BabbleBoss["Cannon Master Willey"], "STRATCannonMasterWilley" },
		{ BabbleBoss["Archivist Galford"], "STRATArchivistGalford" },
		{ BabbleBoss["Balnazzar"], "STRATBalnazzar" },
		{ AL["Sothos and Jarien"], "STRATSothosJarien" },
		{ AtlasLoot_TableNames["STRATStonespine"][1], "STRATStonespine" },
		{ BabbleBoss["Baroness Anastari"], "STRATBaronessAnastari" },
		{ BabbleBoss["Black Guard Swordsmith"], "STRATBlackGuardSwordsmith" },
		{ AtlasLoot_TableNames["STRATBSPlansCorruption"][1], "STRATBSPlansCorruption" },
		{ BabbleBoss["Nerub'enkan"], "STRATNerubenkan" },
		{ BabbleBoss["Maleki the Pallid"], "STRATMalekithePallid" },
		{ BabbleBoss["Magistrate Barthilas"], "STRATMagistrateBarthilas" },
		{ BabbleBoss["Ramstein the Gorger"], "STRATRamsteintheGorger" },
		{ BabbleBoss["Baron Rivendare"], "STRATBaronRivendare" },
		{ AL["Trash Mobs"], "STRATTrash" },
		{ AL["Set: The Postmaster"], "VWOWSets2" },
	},
	["SunkenTemple"] = {
		{ AtlasLoot_TableNames["STSpawnOfHakkar"][1], "STSpawnOfHakkar" },
		{ AtlasLoot_TableNames["STTrollMinibosses"][1], "STTrollMinibosses" },
		{ BabbleBoss["Atal'alarion"], "STAtalalarion" },
		{ BabbleBoss["Dreamscythe"], "STDreamscythe" },
		{ BabbleBoss["Weaver"], "STWeaver"},
		{ BabbleBoss["Avatar of Hakkar"], "STAvatarofHakkar" },
		{ BabbleBoss["Jammal'an the Prophet"], "STJammalan" },
		{ BabbleBoss["Ogom the Wretched"], "STOgom" },
		{ BabbleBoss["Morphaz"], "STMorphaz" },
		{ BabbleBoss["Hazzas"], "STHazzas" },
		{ BabbleBoss["Shade of Eranikus"], "STEranikus" },
		{ AL["Trash Mobs"], "STTrash" },
	},
	["Uldaman"] = {
		{ BabbleBoss["Digmaster Shovelphlange"], "UldShovelphlange" },
		{ AtlasLoot_TableNames["UldBaelog"][1], "UldBaelog" },
		{ BabbleBoss["Revelosh"], "UldRevelosh" },
		{ BabbleBoss["Ironaya"], "UldIronaya" },
		{ BabbleBoss["Ancient Stone Keeper"], "UldAncientStoneKeeper" },
		{ BabbleBoss["Galgann Firehammer"], "UldGalgannFirehammer" },
		{ BabbleBoss["Grimlok"], "UldGrimlok" },
		{ BabbleBoss["Archaedas"], "UldArchaedas" },
		{ AL["Trash Mobs"], "UldTrash" },
	},
	["ZulGurub"] = {
		{ BabbleBoss["High Priestess Jeklik"], "ZGJeklik" },
		{ BabbleBoss["High Priest Venoxis"], "ZGVenoxis" },
		{ BabbleBoss["High Priestess Mar'li"], "ZGMarli" },
		{ BabbleBoss["Bloodlord Mandokir"], "ZGMandokir" },
		{ BabbleZone["Zul'Gurub"], "ZGEdgeofMadness" },
		{ BabbleBoss["Gahz'ranka"], "ZGGahzranka" },
		{ BabbleBoss["High Priest Thekal"], "ZGThekal" },
		{ BabbleBoss["High Priestess Arlokk"], "ZGArlokk" },
		{ BabbleBoss["Jin'do the Hexxer"], "ZGJindo" },
		{ BabbleBoss["Hakkar"], "ZGHakkar" },
		{ AL["Random Boss Loot"], "ZGShared" },
		{ AL["Trash Mobs"], "ZGTrash1" },
		{ AL["ZG Enchants"], "ZGEnchants" },
	},
	["CoTOldHillsbrad"] = {
		{ "", "CoTHillsbradDrake" },
		{ "", "CoTHillsbradSkarloc" },
		{ "", "CoTHillsbradHunter" },
		{ AL["Trash Mobs"], "CoTTrash" },
	},
	["CoTBlackMorass"] = {
		{ "", "CoTMorassDeja" },
		{ "", "CoTMorassTemporus" },
		{ "", "CoTMorassAeonusHEROIC" },
		{ AL["Trash Mobs"], "CoTTrash" },
	},
	["CoTHyjal"] = {
		{ "", "MountHyjalWinterchill" },
		{ "", "MountHyjalAnetheron" },
		{ "", "MountHyjalKazrogal" },
		{ "", "MountHyjalAzgalor" },
		{ "", "MountHyjalArchimonde" },
		{ AL["Trash Mobs"], "MountHyjalTrash" },
	},
	["DireMaulEast"] = {
		{ BabbleBoss["Pusillin"], "DMEPusillin" },
		{ BabbleBoss["Zevrim Thornhoof"], "DMEZevrimThornhoof" },
		{ BabbleBoss["Hydrospawn"], "DMEHydro" },
		{ BabbleBoss["Lethtendris"], "DMELethtendris" },
		{ BabbleBoss["Pimgib"], "DMEPimgib" },
		{ BabbleBoss["Alzzin the Wildshaper"], "DMEAlzzin" },
		{ BabbleBoss["Isalien"], "DMEIsalien" },
		{ AL["Trash Mobs"], "DMETrash" },
		{ AL["Dire Maul Books"], "DMBooks" },
	},
	["DireMaulWest"] = {
		{ BabbleBoss["Tendris Warpwood"], "DMWTendrisWarpwood" },
		{ BabbleBoss["Illyanna Ravenoak"], "DMWIllyannaRavenoak" },
		{ BabbleBoss["Magister Kalendris"], "DMWMagisterKalendris" },
		{ BabbleBoss["Tsu'zee"], "DMWTsuzee" },
		{ BabbleBoss["Immol'thar"], "DMWImmolthar" },
		{ BabbleBoss["Lord Hel'nurath"], "DMWHelnurath" },
		{ BabbleBoss["Prince Tortheldrin"], "DMWPrinceTortheldrin" },
		{ AL["Trash Mobs"], "DMWTrash" },
		{ AL["Dire Maul Books"], "DMBooks" },
	},
	["DireMaulNorth"] = {
		{ BabbleBoss["Guard Mol'dar"], "DMNGuardMoldar" },
		{ BabbleBoss["Stomper Kreeg"], "DMNStomperKreeg" },
		{ BabbleBoss["Guard Fengus"], "DMNGuardFengus" },
		{ AtlasLoot_TableNames["DMNThimblejack"][1], "DMNThimblejack" },
		{ BabbleBoss["Guard Slip'kik"], "DMNGuardSlipkik" },
		{ BabbleBoss["Captain Kromcrush"], "DMNCaptainKromcrush" },
		{ BabbleBoss["King Gordok"], "DMNKingGordok" },
		{ BabbleBoss["Cho'Rush the Observer"], "DMNChoRush" },
		{ AL["Tribute Run"], "DMNTRIBUTERUN" },
		{ AL["Dire Maul Books"], "DMBooks" },
	},
	["RuinsofAQ"] = {
		{ BabbleBoss["Kurinnaxx"], "AQ20Kurinnaxx" },
		{ BabbleBoss["General Rajaxx"], "AQ20Rajaxx" },
		{ BabbleBoss["Moam"], "AQ20Moam" },
		{ BabbleBoss["Buru the Gorger"], "AQ20Buru" },
		{ BabbleBoss["Ayamiss the Hunter"], "AQ20Ayamiss" },
		{ BabbleBoss["Ossirian the Unscarred"], "AQ20Ossirian" },
		{ AL["Trash Mobs"], "AQ20Trash" },
		{ AL["Class Books"], "AQ20ClassBooks" },
		{ AL["AQ Enchants"], "AQEnchants" },
		{ AL["Ruins of Ahn'Qiraj Sets"], "AQ20Sets1" },
	},
	["TempleofAQ"] = {
		{ BabbleBoss["The Prophet Skeram"], "AQ40Skeram" },
		{ BabbleBoss["The Bug Family"], "AQ40Vem" },
		{ BabbleBoss["Battleguard Sartura"], "AQ40Sartura" },
		{ BabbleBoss["Fankriss the Unyielding"], "AQ40Fankriss" },
		{ BabbleBoss["Viscidus"], "AQ40Viscidus" },
		{ BabbleBoss["Princess Huhuran"], "AQ40Huhuran" },
		{ BabbleBoss["The Twin Emperors"], "AQ40Emperors" },
		{ BabbleBoss["Ouro"], "AQ40Ouro" },
		{ BabbleBoss["C'Thun"], "AQ40CThun" },
		{ AL["Trash Mobs"], "AQ40Trash1" },
		{ AL["AQ Enchants"], "AQEnchants" },
		{ AL["AQ Opening Quest Chain"], "AQOpening" },
	},
	["ZulFarrak"] = {
		{ BabbleBoss["Antu'sul"], "ZFAntusul" },
		{ BabbleBoss["Theka the Martyr"], "ZFThekatheMartyr" },
		{ BabbleBoss["Witch Doctor Zum'rah"], "ZFWitchDoctorZumrah" },
		{ BabbleBoss["Nekrum Gutchewer"], "ZFNekrumGutchewer" },
		{ BabbleBoss["Shadowpriest Sezz'ziz"], "ZFSezzziz" },
		{ BabbleBoss["Dustwraith"], "ZFDustwraith" },
		{ BabbleBoss["Sergeant Bly"], "ZFSergeantBly" },
		{ BabbleBoss["Sandfury Executioner"], "ZFSandfury" },
		{ BabbleBoss["Hydromancer Velratha"], "ZFHydromancerVelratha" },
		{ BabbleBoss["Gahz'rilla"], "ZFGahzrilla" },
		{ BabbleBoss["Chief Ukorz Sandscalp"], "ZFChiefUkorzSandscalp" },
		{ BabbleBoss["Zerillis"], "ZFZerillis" },
		{ AL["Trash Mobs"], "ZFTrash" },
	},
	["AuchManaTombs"] = {
		{ "", "AuchManaPandemonius" },
		{ "", "AuchManaTavarok" },
		{ "", "AuchManaNexusPrince" },
		{ "", "AuchManaYorHEROIC" },
		{ AL["Trash Mobs"], "AuchTrash" },
	},
	["AuchCrypts"] = {
		{ "", "AuchCryptsShirrak" },
		{ "", "AuchCryptsExarch" },
		{ "", "AuchCryptsAvatarHEROIC" },
		{ AL["Trash Mobs"], "AuchTrash" },
	},
	["AuchSethekk"] = {
		{ "", "AuchSethekkDarkweaver" },
		{ "", "AuchSethekkTalonKing" },
		{ "", "AuchSethekkRavenGodHEROIC" },
		{ AL["Trash Mobs"], "AuchTrash" },
	},
	["AuchShadowLab"] = {
		{ "", "AuchShadowHellmaw" },
		{ "", "AuchShadowBlackheart" },
		{ "", "AuchShadowGrandmaster" },
		{ "", "AuchShadowMurmur" },
		{ AL["Trash Mobs"], "AuchTrash" },
	},
	["BlackTemple"] = {
		{ "", "BTNajentus" },
		{ "", "BTSupremus" },
		{ "", "BTAkama" },
		{ "", "BTGorefiend" },
		{ "", "BTBloodboil" },
		{ "", "BTEssencofSouls" },
		{ "", "BTShahraz" },
		{ "", "BTCouncil" },
		{ "", "BTIllidanStormrage" },
		{ AL["BT Patterns/Plans"], "BTPatterns" },
		{ AL["Trash Mobs"], "BTTrash" },
	},
	["CFRSlavePens"] = {
		{ "", "CFRSlaveMennu" },
		{ "", "CFRSlaveRokmar" },
		{ "", "CFRSlaveQuagmirran" },
		{ "", "LordAhune" },
	},
	["CFRUnderbog"] = {
		{ "", "CFRUnderHungarfen" },
		{ "", "CFRUnderGhazan" },
		{ "", "CFRUnderSwamplord" },
		{ "", "CFRUnderStalker" },
	},
	["CFRSteamvault"] = {
		{ "", "CFRSteamThespia" },
		{ "", "CFRSteamSteamrigger" },
		{ "", "CFRSteamWarlord" },
		{ AL["Trash Mobs"], "CFRSteamTrash" },
	},
	["CFRSerpentshrine"] = {
		{ "", "CFRSerpentHydross" },
		{ "", "CFRSerpentLurker" },
		{ "", "CFRSerpentLeotheras" },
		{ "", "CFRSerpentKarathress" },
		{ "", "CFRSerpentMorogrim" },
		{ "", "CFRSerpentVashj" },
		{ AL["Trash Mobs"], "CFRSerpentTrash" },
	},
	["CFRSerpentshrine10"] = {
		{ "", "CFRSerpentHydross10" },
		{ "", "CFRSerpentLurker10" },
		{ "", "CFRSerpentLeotheras10" },
		{ "", "CFRSerpentKarathress10" },
		{ "", "CFRSerpentMorogrim10" },
		{ "", "CFRSerpentVashj10" },
		{ AL["Trash Mobs"], "CFRSerpentTrash10" },
	},
	["Gruul"] = {
		{ "", "GruulsLairHighKingMaulgar" },
		{ "", "GruulGruul" },
	},
	["HCRamparts"] = {
		{ "", "HCRampWatchkeeper" },
		{ "", "HCRampOmor" },
		{ "", "HCRampVazruden" },
	},
	["HCFurnace"] = {
		{ "", "HCFurnaceMaker" },
		{ "", "HCFurnaceBroggok" },
		{ "", "HCFurnaceBreaker" },
	},
	["HCShatteredHalls"] = {
		{ "", "HCHallsNethekurse" },
		{ "", "HCHallsPorungHEROIC" },
		{ "", "HCHallsOmrogg" },
		{ "", "HCHallsKargathHEROIC" },
		{ AL["Trash Mobs"], "HCHallsTrash" },
	},
	["TKMech"] = {
		{ "", "TKMechCacheoftheLegionHEROIC" },
		{ "", "TKMechCapacitus" },
		{ "", "TKMechSepethrea" },
		{ "", "TKMechCalc" },
		{ AL["Trash Mobs"], "TKTrash" },
	},
	["TKBot"] = {
		{ "", "TKBotSarannis" },
		{ "", "TKBotFreywinn" },
		{ "", "TKBotThorngrin" },
		{ "", "TKBotLaj" },
		{ "", "TKBotSplinter" },
		{ AL["Trash Mobs"], "TKTrash" },
	},
	["TKArc"] = {
		{ "", "TKArcUnbound" },
		{ "", "TKArcScryer" },
		{ "", "TKArcDalliah" },
		{ "", "TKArcHarbingerHEROIC" },
		{ AL["Trash Mobs"], "TKTrash" },
	},
	["TKEye"] = {
		{ "", "TKEyeAlar" },
		{ "", "TKEyeVoidReaver" },
		{ "", "TKEyeSolarian" },
		{ "", "TKEyeKaelthas" },
		{ "", "TKEyeLegendaries" },
		{ AL["Trash Mobs"], "TKEyeTrash" },
	},
	["TKEye10"] = {
		{ "", "TKEyeAlar10" },
		{ "", "TKEyeVoidReaver10" },
		{ "", "TKEyeSolarian10" },
		{ "", "TKEyeKaelthas10" },
		{ "", "TKEyeLegendaries10" },
		{ AL["Trash Mobs"], "TKEyeTrash10" },
	},
	["ZulAman"] = {
		{ "", "ZANalorakk" },
		{ "", "ZAAkilZon" },
		{ "", "ZAJanAlai" },
		{ "", "ZAHalazzi" },
		{ "", "ZAMalacrass" },
		{ "", "ZAZuljin" },
		{ AL["Timed Reward Chest"], "ZATimedChest" },
		{ AL["Trash Mobs"], "ZATrash" },
	},
	["SunwellPlateau"] = {
		{ "", "SPKalecgos" },
		{ "", "SPBrutallus" },
		{ "", "SPFelmyst" },
		{ "", "SPEredarTwins" },
		{ "", "SPMuru" },
		{ "", "SPKiljaeden" },
		{ "", "SPPatterns" },
		{ AL["Trash Mobs"], "SPTrash" },
	},
	["Ahnkahet"] = {
		{ "", "AhnkahetNadox" },
		{ "", "AhnkahetTaldaram" },
		{ "", "AhnkahetAmanitarHEROIC" },
		{ "", "AhnkahetJedoga" },
		{ "", "AhnkahetVolazj" },
		{ "", "AhnkahetTrash" },
	},
	["AzjolNerub"] = {
		{ "", "AzjolNerubKrikthir" },
		{ "", "AzjolNerubHadronox" },
		{ "", "AzjolNerubAnubarak" },
		{ "", "AzjolNerubTrash" },
	},
	["CoTStratholme"] = {
		{ "", "CoTStratholmeMeathook" },
		{ "", "CoTStratholmeEpoch" },
		{ "", "CoTStratholmeSalramm" },
		{ "", "CoTStratholmeInfiniteCorruptorHEROIC" },
		{ "", "CoTStratholmeMalGanis" },
		{ "", "CoTStratholmeTrash" },
	},
	["DrakTharonKeep"] = {
		{ "", "DrakTharonKeepTrollgore" },
		{ "", "DrakTharonKeepNovos" },
		{ "", "DrakTharonKeepKingDred" },
		{ "", "DrakTharonKeepTharonja" },
		{ "", "DrakTharonKeepTrash" },
	},
	["Gundrak"] = {
		{ "", "GundrakSladran" },
		{ "", "GundrakColossus" },
		{ "", "GundrakMoorabi" },
		{ "", "GundrakEckHEROIC" },
		{ "", "GundrakGaldarah" },
		{ "", "GundrakTrash" },
	},
	["HallsofLightning"] = {
		{ "", "HallsofLightningBjarngrim" },
		{ "", "HallsofLightningVolkhan" },
		{ "", "HallsofLightningIonar" },
		{ "", "HallsofLightningLoken" },
		{ "", "HallsofLightningTrash" },
	},
	["HallsofStone"] = {
		{ "", "HallsofStoneMaiden" },
		{ "", "HallsofStoneKrystallus" },
		{ "", "HallsofStoneTribunal" },
		{ "", "HallsofStoneSjonnir" },
		{ "", "HallsofStoneTrash" },
	},
	["Ulduar"] = {
		{ "", "UlduarLeviathan" },
		{ "", "UlduarIgnis" },
		{ "", "UlduarRazorscale" },
		{ "", "UlduarDeconstructor" },
		{ "", "UlduarIronCouncil" },
		{ "", "UlduarKologarn" },
		{ "", "UlduarAuriaya" },
		{ "", "UlduarHodir" },
		{ "", "UlduarThorim" },
		{ "", "UlduarFreya" },
		{ "", "UlduarMimiron" },
		{ "", "UlduarVezax" },
		{ "", "UlduarYoggSaron" },
		{ "", "UlduarAlgalon" },
		{ "", "UlduarTrash" },
		{ "", "UlduarPatterns" },
	},
	["UtgardeKeep"] = {
		{ "", "UtgardeKeepKeleseth" },
		{ "", "UtgardeKeepSkarvald" },
		{ "", "UtgardeKeepIngvar" },
		{ "", "UtgardeKeepTrash" },
	},
	["UtgardePinnacle"] = {
		{ "", "UPSkadi" },
		{ "", "UPYmiron" },
		{ "", "UPSorrowgrave" },
		{ "", "UPPalehoof" },
		{ "", "UPTrash" },
	},
	["TheVioletHold"] = {
		{ "", "VioletHoldErekem" },
		{ "", "VioletHoldZuramat" },
		{ "", "VioletHoldXevozz" },
		{ "", "VioletHoldIchoron" },
		{ "", "VioletHoldMoragg" },
		{ "", "VioletHoldLavanthor" },
		{ "", "VioletHoldCyanigosa" },
		{ "", "VioletHoldTrash" },
	},
	["TheOculus"] = {
		{ "", "OcuDrakos" },
		{ "", "OcuUrom" },
		{ "", "OcuCloudstrider" },
		{ "", "OcuEregos" },
		{ "", "OcuTrash" },
	},
	["TrialoftheChampion"] = {
		{ "", "TrialoftheChampionChampions" },
		{ "", "TrialoftheChampionConfessorPaletress" },
		{ "", "TrialoftheChampionEadricthePure" },
		{ "", "TrialoftheChampionBlackKnight" },
	},
	["TrialoftheCrusader_A"] = {
		{ BabbleBoss["The Beasts of Northrend"], "TrialoftheCrusaderNorthrendBeasts_A" },
		{ BabbleBoss["Lord Jaraxxus"], "TrialoftheCrusaderLordJaraxxus_A" },
		{ AL["Faction Champions"], "TrialoftheCrusaderFactionChampions_A" },
		{ BabbleBoss["The Twin Val'kyr"], "TrialoftheCrusaderTwinValkyrs_A" },
		{ BabbleBoss["Anub'arak"], "TrialoftheCrusaderAnubarak_A" },
		{ AL["Tribute Run"], "TrialoftheCrusaderTribute_AHEROIC" },
		{ AL["Trial of the Crusader Patterns/Plans"], "TrialoftheCrusaderPatterns_A" },
	},
	["VaultofArchavon_A"] = {
		{ BabbleBoss["Archavon the Stone Watcher"], "VaultofArchavonArchavon1" },
		{ BabbleBoss["Emalon the Storm Watcher"], "VaultofArchavonEmalon1" },
		{ BabbleBoss["Koralon the Flame Watcher"], "VaultofArchavonKoralon1_A" },
		{ BabbleBoss["Toravon the Ice Watcher"], "VaultofArchavonToravon1" },
		--{ BabbleBoss["Elem"], "VaultofArchavonElem1" },
	},
	["Naxxramas80"] = {
		{ AtlasLoot_TableNames["Naxx80Patchwerk"][1].." ("..AL["Construct Quarter"]..")", "Naxx80Patchwerk" },
		{ AtlasLoot_TableNames["Naxx80Grobbulus"][1].." ("..AL["Construct Quarter"]..")", "Naxx80Grobbulus" },
		{ AtlasLoot_TableNames["Naxx80Gluth1"][1].." ("..AL["Construct Quarter"]..")", "Naxx80Gluth1" },
		{ AtlasLoot_TableNames["Naxx80Thaddius"][1].." ("..AL["Construct Quarter"]..")", "Naxx80Thaddius" },
		{ AtlasLoot_TableNames["Naxx80AnubRekhan"][1].." ("..AL["Arachnid Quarter"]..")", "Naxx80AnubRekhan" },
		{ AtlasLoot_TableNames["Naxx80Faerlina"][1].." ("..AL["Arachnid Quarter"]..")", "Naxx80Faerlina" },
		{ AtlasLoot_TableNames["Naxx80Maexxna"][1].." ("..AL["Arachnid Quarter"]..")", "Naxx80Maexxna" },
		{ AtlasLoot_TableNames["Naxx80Razuvious"][1].." ("..AL["Military Quarter"]..")", "Naxx80Razuvious" },
		{ AtlasLoot_TableNames["Naxx80Gothik"][1].." ("..AL["Military Quarter"]..")", "Naxx80Gothik" },
		{ AtlasLoot_TableNames["Naxx80FourHorsemen"][1].." ("..AL["Military Quarter"]..")", "Naxx80FourHorsemen" },
		{ AtlasLoot_TableNames["Naxx80Noth"][1].." ("..AL["Plague Quarter"]..")", "Naxx80Noth" },
		{ AtlasLoot_TableNames["Naxx80Heigan"][1].." ("..AL["Plague Quarter"]..")", "Naxx80Heigan" },
		{ AtlasLoot_TableNames["Naxx80Loatheb"][1].." ("..AL["Plague Quarter"]..")", "Naxx80Loatheb" },
		{ AtlasLoot_TableNames["Naxx80Sapphiron"][1].." ("..AL["Frostwyrm Lair"]..")", "Naxx80Sapphiron" },
		{ AtlasLoot_TableNames["Naxx80KelThuzad"][1].." ("..AL["Frostwyrm Lair"]..")", "Naxx80KelThuzad" },
		{ "", "Naxx80Trash" },
	},
	["TheNexus"] = {
		{ "", "TheNexusTelestra" },
		{ "", "TheNexusAnomalus"},
		{ "", "TheNexusOrmorok" },
		{ "", "TheNexusKolurgStoutbeardHEROIC"},
		{ "", "TheNexusKeristrasza" },
	},
	["WorldBosses"] = {
		{ "", "Norigorn_x2" },
		{ "", "WorldBossesClassic"},
		{ "", "WorldBossesBC" },
		{ "", "DEmeriss"},
		{ "", "DLethon" },
		{ "", "DTaerar" },
		{ "", "DYsondre" },
	},
	["ForgeofSouls"] = {
		{ "", "FoSBronjahm" },
		{ "", "FoSDevourer" },
		{ "", "FHTrashMobs" },
	},
	["PitofSaron"] = {
		{ "", "PoSGarfrost" },
		{ "", "PoSKrickIck" },
		{ "", "PoSTyrannus" },
		{ "", "FHTrashMobs" },
	},
	["HallsofReflection"] = {
		{ "", "HoRFalric" },
		{ "", "HoRMarwyn" },
		{ "", "HoRLichKing" },
		{ "", "FHTrashMobs" },
	},
	["IcecrownCitadel"] = {
		{ "", "ICCLordMarrowgar" },
		{ "", "ICCLadyDeathwhisper" },
		{ "", "ICCGunshipBattle" },
		{ "", "ICCSaurfang" },
		{ "", "ICCFestergut" },
		{ "", "ICCRotface" },
		{ "", "ICCPutricide" },
		{ "", "ICCCouncil" },
		{ "", "ICCLanathel" },
		{ "", "ICCValithria" },
		{ "", "ICCSindragosa" },
		{ "", "ICCLichKing" },
		{ "", "ICCJaina25ManHEROIC" },
		{ "", "ICCTrash25Man" },
	},
	["BronzeSanctuary"] = {
		{ "", "Imporus" },
		{ "", "Elonus" },
		{ "", "Murozond" },
		{ "", "GrainOfSandOfLost" },
	},
	["Tol'Garod Prison2"] = {
		{ "", "Gogonash_258" },
		{ "", "Xtrax Mind Absorber_258" },
		{ "", "Magic Eater_258" },
		{ "", "Enchanting_Tol'Garod" },
		},
	["Tol'Garod Prison3"] = {
		{ "", "Gogonash_271" },
		{ "", "Xtrax Mind Absorber_271" },
		{ "", "Magic Eater_271" },
		{ "", "Enchanting_Tol'Garod" },
		},
	["Tol'Garod Prison4"] = {
		{ "", "Gogonash_284" },
		{ "", "Xtrax Mind Absorber_284" },
		{ "", "Magic Eater_284" },
		{ "", "Enchanting_Tol'Garod" },
		
	},
	["Tol'Garod Prison5"] = {
		{ "", "Gogonash_245" },
		{ "", "Xtrax Mind Absorber_245" },
		{ "", "Magic Eater_245" },
		{ "", "Enchanting_Tol'Garod" },
		
	},
	["Zort"] = {
		{ "", "Zort" },			
	},
	["DAILYMENU"] = {
		{ "", "DAILYMENU" },			
	},
	-- Epochal Mode
	["EpochalWeapon"] = {
		{ "", "EpochalWeapon200" },	
		{ "", "EpochalWeapon203" },
		{ "", "EpochalWeapon206" },
		{ "", "EpochalWeapon209" },
		{ "", "EpochalWeapon213" },
		{ "", "EpochalWeapon216" },
		{ "", "EpochalWeapon219" },
		{ "", "EpochalWeapon222" },
		{ "", "EpochalWeapon226" },
		{ "", "EpochalWeapon229" },
		{ "", "EpochalWeapon232" },
		{ "", "EpochalWeapon236" },
		{ "", "EpochalWeapon239" },
		{ "", "EpochalWeapon242" },
		{ "", "EpochalWeapon245" },
		{ "", "EpochalWeapon247" },
		{ "", "EpochalWeapon249" },
		{ "", "EpochalWeapon251" },
		{ "", "EpochalWeapon253" },
		{ "", "EpochalWeapon256" },
		{ "", "EpochalWeapon258" },
		{ "", "EpochalWeapon260" },	
	},
	["EpochalCloth"] = {
		{ "", "EpochalCloth200" },	
		{ "", "EpochalCloth203" },
		{ "", "EpochalCloth206" },
		{ "", "EpochalCloth209" },
		{ "", "EpochalCloth213" },
		{ "", "EpochalCloth216" },
		{ "", "EpochalCloth219" },
		{ "", "EpochalCloth222" },
		{ "", "EpochalCloth226" },
		{ "", "EpochalCloth229" },
		{ "", "EpochalCloth232" },
		{ "", "EpochalCloth236" },
		{ "", "EpochalCloth239" },
		{ "", "EpochalCloth242" },
		{ "", "EpochalCloth245" },
		{ "", "EpochalCloth247" },
		{ "", "EpochalCloth249" },
		{ "", "EpochalCloth251" },
		{ "", "EpochalCloth253" },
		{ "", "EpochalCloth256" },
		{ "", "EpochalCloth258" },
		{ "", "EpochalCloth260" },	
	},
	["EpochalLeather"] = {
		{ "", "EpochalLeather200" },	
		{ "", "EpochalLeather203" },
		{ "", "EpochalLeather206" },
		{ "", "EpochalLeather209" },
		{ "", "EpochalLeather213" },
		{ "", "EpochalLeather216" },
		{ "", "EpochalLeather219" },
		{ "", "EpochalLeather222" },
		{ "", "EpochalLeather226" },
		{ "", "EpochalLeather229" },
		{ "", "EpochalLeather232" },
		{ "", "EpochalLeather236" },
		{ "", "EpochalLeather239" },
		{ "", "EpochalLeather242" },
		{ "", "EpochalLeather245" },
		{ "", "EpochalLeather247" },
		{ "", "EpochalLeather249" },
		{ "", "EpochalLeather251" },
		{ "", "EpochalLeather253" },
		{ "", "EpochalLeather256" },
		{ "", "EpochalLeather258" },
		{ "", "EpochalLeather260" },	
	},
	["EpochalMail"] = {
		{ "", "EpochalMail200" },	
		{ "", "EpochalMail203" },
		{ "", "EpochalMail206" },
		{ "", "EpochalMail209" },
		{ "", "EpochalMail213" },
		{ "", "EpochalMail216" },
		{ "", "EpochalMail219" },
		{ "", "EpochalMail222" },
		{ "", "EpochalMail226" },
		{ "", "EpochalMail229" },
		{ "", "EpochalMail232" },
		{ "", "EpochalMail236" },
		{ "", "EpochalMail239" },
		{ "", "EpochalMail242" },
		{ "", "EpochalMail245" },
		{ "", "EpochalMail247" },
		{ "", "EpochalMail249" },
		{ "", "EpochalMail251" },
		{ "", "EpochalMail253" },
		{ "", "EpochalMail256" },
		{ "", "EpochalMail258" },
		{ "", "EpochalMail260" },	
	},	
	["EpochalPlait"] = {
		{ "", "EpochalPlait200" },	
		{ "", "EpochalPlait203" },
		{ "", "EpochalPlait206" },
		{ "", "EpochalPlait209" },
		{ "", "EpochalPlait213" },
		{ "", "EpochalPlait216" },
		{ "", "EpochalPlait219" },
		{ "", "EpochalPlait222" },
		{ "", "EpochalPlait226" },
		{ "", "EpochalPlait229" },
		{ "", "EpochalPlait232" },
		{ "", "EpochalPlait236" },
		{ "", "EpochalPlait239" },
		{ "", "EpochalPlait242" },
		{ "", "EpochalPlait245" },
		{ "", "EpochalPlait247" },
		{ "", "EpochalPlait249" },
		{ "", "EpochalPlait251" },
		{ "", "EpochalPlait253" },
		{ "", "EpochalPlait256" },
		{ "", "EpochalPlait258" },
		{ "", "EpochalPlait260" },	
	},
	["EpochalСloak"] = {
		{ "", "EpochalСloak200" },	
		{ "", "EpochalСloak203" },
		{ "", "EpochalСloak206" },
		{ "", "EpochalСloak209" },
		{ "", "EpochalСloak213" },
		{ "", "EpochalСloak216" },
		{ "", "EpochalСloak219" },
		{ "", "EpochalСloak222" },
		{ "", "EpochalСloak226" },
		{ "", "EpochalСloak229" },
		{ "", "EpochalСloak232" },
		{ "", "EpochalСloak236" },
		{ "", "EpochalСloak239" },
		{ "", "EpochalСloak242" },
		{ "", "EpochalСloak245" },
		{ "", "EpochalСloak247" },
		{ "", "EpochalСloak249" },
		{ "", "EpochalСloak251" },
		{ "", "EpochalСloak253" },
		{ "", "EpochalСloak256" },
		{ "", "EpochalСloak258" },
		{ "", "EpochalСloak260" },	
	},
	["EpochalNeck"] = {
		{ "", "EpochalNeck200" },	
		{ "", "EpochalNeck203" },
		{ "", "EpochalNeck206" },
		{ "", "EpochalNeck209" },
		{ "", "EpochalNeck213" },
		{ "", "EpochalNeck216" },
		{ "", "EpochalNeck219" },
		{ "", "EpochalNeck222" },
		{ "", "EpochalNeck226" },
		{ "", "EpochalNeck229" },
		{ "", "EpochalNeck232" },
		{ "", "EpochalNeck236" },
		{ "", "EpochalNeck239" },
		{ "", "EpochalNeck242" },
		{ "", "EpochalNeck245" },
		{ "", "EpochalNeck247" },
		{ "", "EpochalNeck249" },
		{ "", "EpochalNeck251" },
		{ "", "EpochalNeck253" },
		{ "", "EpochalNeck256" },
		{ "", "EpochalNeck258" },
		{ "", "EpochalNeck260" },	
	},
		["EpochalRight"] = {
		{ "", "EpochalRight200" },	
		{ "", "EpochalRight203" },
		{ "", "EpochalRight206" },
		{ "", "EpochalRight209" },
		{ "", "EpochalRight213" },
		{ "", "EpochalRight216" },
		{ "", "EpochalRight219" },
		{ "", "EpochalRight222" },
		{ "", "EpochalRight226" },
		{ "", "EpochalRight229" },
		{ "", "EpochalRight232" },
		{ "", "EpochalRight236" },
		{ "", "EpochalRight239" },
		{ "", "EpochalRight242" },
		{ "", "EpochalRight245" },
		{ "", "EpochalRight247" },
		{ "", "EpochalRight249" },
		{ "", "EpochalRight251" },
		{ "", "EpochalRight253" },
		{ "", "EpochalRight256" },
		{ "", "EpochalRight258" },
		{ "", "EpochalRight260" },	
	},
};